### ISSUE TITLE
Not injecting JS when parameters added to URL

### ISSUE THREAD

**Issue by q-a-z** [JonCooperWorks/judas#5]
I've set up to mirror xxx.com, on yyy.com
URL xxx.com/test exists.
When i type yyy.com/test mirroring working, but no JS injected

**Comment by q-a-z** [comment]
my bad, xxx.com/test has 301 redirect
is there any way to inject there?

**Comment by JonCooperWorks** [comment]
Does the redirect go to a different domain?

**Comment by JonCooperWorks** [comment]
See #7.
This rewrites the location. Thanks for spotting this edge case

**Comment by q-a-z** [comment]
-Does the redirect go to a different domain?
Yes

**Comment by JonCooperWorks** [comment]
I've added a fix for this in master

**Comment by q-a-z** [comment]
Awesome!
Thanks!
