### ISSUE TITLE
......

### ISSUE THREAD

**Issue by 294ru84** [JonCooperWorks/judas#6]

**Comment by JonCooperWorks** [comment]
Hi,

It's meant to be used at the root URL.
To clone login.php, just add /login.php?link=123 to the phishing site URL.

What website gives you the EOF error?

**Comment by ankushgoel27** [comment]
I am having the same issue. The site comes up fine but then there is an error "Error dumping request to console.". after that, the phishing site stops working and the other errors starts "Error parsing request: EOF"

**Comment by JonCooperWorks** [comment]
What command are you using to start Judas?

**Comment by ankushgoel27** [comment]
./judas -cert /etc/letsencrypt/live/site.com/cert.pem -private-key /etc/letsencrypt/live/site.com/privkey.pem -address 0.0.0.0:443 -target https://accounts.google.com

**Comment by ankushgoel27** [comment]
-s ./dump_creds.py

**Comment by ankushgoel27** [comment]
also, it seems like the proxy doesn't follow redirects.

**Comment by ankushgoel27** [comment]
any update?

**Comment by JonCooperWorks** [comment]
Hey,

Sorry about the delay, I've been busy lately.

I started looking into the problem and it's related to the location header.
After patching that it seems the proxy has an issue with reading a HTTP
request body twice.

I'm still working on a fix

**Comment by JonCooperWorks** [comment]
Hey, I finally fixed this issue.
