### ISSUE TITLE
Cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by molecul** [JonCooperWorks/judas#9]
Hi, 

I have a some troubles when target website use self-signed/expired certificate.

> 
2019/01/19 03:30:17 Setting target to https://192.168.1.1:443
2019/01/19 03:30:17 Listening on: http://0.0.0.0:8443
2019/01/19 03:30:21 Proxy error: Get https://192.168.1.1:443/: x509: cannot validate certificate for 192.168.1.37 because it doesn't contain any IP SANs
2019/01/19 03:30:21 Proxy error: Get https://192.168.1.1:443/: x509: cannot validate certificate for 192.168.1.37 because it doesn't contain any IP SANs
>

**Comment by molecul** [comment]
Provide a fix https://github.com/JonCooperWorks/judas/pull/10
Please merge it, thank you!

**Comment by JonCooperWorks** [comment]
Thanks for this fix. I've merged it.
